routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/index2', function () {
    return view('index2');
});

Route::get('/input', function () {
    return view('input');
});

Route::get('/team', function () {
    return view('team1')->with(
        ['hideBeforeInit' => true]
    );
});

Route::get('/mobile', function () {
    return view('mobile');
});

//Route::get('/mails', [MailController::class,'index'])->middleware(['auth']);

Route::get('/select', function () {
    return view('select');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
    Route::get('/select-avatar', function() {
        return view('admin.select-avatar');
    });
    Route::get('/mails', [MailController::class,'index']);
});


require __DIR__.'/auth.php';

app/Models/Mail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mail extends Model
{
    use HasFactory;
    protected $table = 'SOT_MAILS';
    protected $fillable = ['email', 'name'];        
    protected $primaryKey = 'id';    
}

app/Models/SotUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SotUser extends Model
{
    use HasFactory;

    protected $table = 'sot_users';
    protected $fillable = ['firstname', 'email','gender','avatar_name','character'];        
    protected $primaryKey = 'id';     
    
        /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $table = 'sot_admin';
    public $timestamps = false;
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password', 'avatar','active'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Mail;

class MailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mails = Mail::all();
        return view('admin.mails', compact('mails'));
        //return response()->json($mails);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'name' => 'required|string',
        ]);

        $email = Mail::create(['email' => $request->email, 'name' => $request->name]);
        return response()->json($email);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/SotUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\SotUser;
use Illuminate\Http\Request;

class SotUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'firstname' => 'required|string',
            'email' => 'required|email|unique:sot_users',            
            'avatar_name' => 'required|string',
            'character' => 'required|string',
        ]);
               
        $sotUser = SotUser::create([
            'firstname' => $request->firstname, 
            'email' => $request->email,  
            'gender' => $request->character == 'girl' ? 'f' : 'm', 
            'avatar_name' => $request->avatar_name, 
            'character' => $request->character
        ]);
        return response()->json($sotUser);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SotUser  $sotUser
     * @return \Illuminate\Http\Response
     */
    public function show(SotUser $sotUser)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SotUser  $sotUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SotUser $sotUser)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SotUser  $sotUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(SotUser $sotUser)
    {
        //
    }
}

app/Http/Livewire/MailsTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Mail;
use Livewire\Component;
use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;

class MailsTable extends DataTableComponent
{

    protected $model = Mail::class;

    public function configure(): void {        
        $this->setPrimaryKey('id');
    }
    
    public function columns(): array
    {
        return [   
            Column::make('Name', 'name')->sortable()
            ->searchable(),             
            Column::make('E-mail', 'email')->sortable()
            ->searchable(),            
            Column::make('Created', 'created_at')->sortable()
            ->searchable(),
        ];
    }    
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/mails.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <livewire:mails-table />
        </div>
    </div>
</x-app-layout>

resources/views/admin/select-avatar.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12 text-white">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="text-center text-white qb-one mb-6">ENTER METAVERSE</div>
            <div class="sm:grid sm:grid-cols-5 space-x-4">
                <div class="col-span-1 gradient rounded-xl pb-6 pt-10 relative">
                    <label for="pinkgirl2">
                        <input id="pinkgirl2" type="checkbox" class="form-checkbox absolute right-3 top-2 rounded-sm bg-transparent border checked:border-white checked:text-black" value="">
                        <img src="/img/avatar/pinkgirl2.png" />
                    </label>
                </div>
                <div class="col-span-1 gradient rounded-xl pb-6 pt-10 relative">
                    <label for="redguy">
                        <input id="redguy" class="form-checkbox absolute right-3 top-2 rounded-sm bg-transparent border checked:border-white checked:text-black" type="checkbox" value="">
                        <img src="/img/avatar/redguy.png" />
                    </label>
                </div>
                <div class="col-span-1 gradient rounded-xl pb-6 pt-10 relative">
                    <label for="skeleton">
                        <input id="skeleton" class="form-checkbox absolute right-3 top-2 rounded-sm bg-transparent border checked:border-white checked:text-black" type="checkbox" value="">
                        <img src="/img/avatar/skeleton.png" />
                    </label>
                </div>
                <div class="col-span-1 gradient rounded-xl pb-6 pt-10 relative">
                    <label for="grunge">
                        <input id="grunge" class="form-checkbox absolute right-3 top-2 rounded-sm bg-transparent border checked:border-white checked:text-black" type="checkbox" value="">
                        <img src="/img/avatar/grunge.png" />
                    </label>
                </div>
                <div class="col-span-1 gradient rounded-xl pb-6 pt-10 relative">
                    <label for="hoodie">
                        <input id="hoodie" class="form-checkbox absolute right-3 top-2 rounded-sm bg-transparent border checked:border-white checked:text-black" type="checkbox" value="">
                        <img src="/img/avatar/hoodie.png" />
                    </label>
                </div>
            </div>

            <div class="gradient rounded-xl w-full relative mt-4">
                <div class="flex flex-col items-center space-y-6 py-8">
                    <input x-model="formData.firstname" class="bg-black border border-gray-500 px-6 py-2 rounded-xl w-2/6" type="text" name="guestname" id="guestname" placeholder="Enter sign message here..." />
                    <input x-model="formData.email" class="bg-black border border-gray-500 px-6 py-2 rounded-xl w-2/6" type="text" name="guestname" id="guestname" placeholder="Avatar name.." />
                    <span><button type="button" @click="submitForm" class="bg-gradient px-16 py-2 rounded-lg hover:bg-red-50">ENTER</button></span>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/index.blade.php
<!DOCTYPE html>
<html>
<head>

    <!-- Global site tag (gtag.js) - Google Ads -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-10881855478"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'AW-10881855478');

    </script>

    <meta charset="utf-8">

    <title>A NFT Play-to-earn-game</title>

    <!--http://www.html5rocks.com/en/mobile/mobifying/-->
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1, minimum-scale=1,maximum-scale=1" />

    <!--https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="format-detection" content="telephone=no">

    <!-- force webkit on 360 -->
    <meta name="renderer" content="webkit" />
    <meta name="force-rendering" content="webkit" />
    <!-- force edge on IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="msapplication-tap-highlight" content="no">

    <!-- force full screen on some browser -->
    <meta name="full-screen" content="yes" />
    <meta name="x5-fullscreen" content="true" />
    <meta name="360-fullscreen" content="true" />

    <!-- force screen orientation on some browser -->
    <meta name="screen-orientation" content="" />
    <meta name="x5-orientation" content="">

    <!--fix fireball/issues/3568 -->
    <!--<meta name="browsermode" content="application">-->
    <meta name="x5-page-mode" content="app">
    <link rel="stylesheet" href="/css/app.css" />
    <link rel="stylesheet" href="/extras/style-desktop.css" />
    <!--<link rel="apple-touch-icon" href=".png" />-->
    <!--<link rel="apple-touch-icon-precomposed" href=".png" />-->

    <!-- <link rel="stylesheet" type="text/css" href="/extras/style-mobile.css" /> -->

    <!--for mobile-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />


    <link rel="icon" href="favicon.ico" />
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<body x-on:resize.window.debounce="isMobile = (window.innerWidth < 1024) ? true : false" x-data="{isMobile: (window.innerWidth < 1024) ? true : false, forceHide: false}" x-init="$nextTick(() => {
        forceHide = (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 0))? true : false;        
    })">
    @include('layout.menu', ['hideBeforeInit' => true])
    <canvas x-show="!isMobile && !forceHide" id="GameCanvas" oncontextmenu="event.preventDefault()" tabindex="0"></canvas>
    <div x-show="!isMobile && !forceHide" id="splash">
        <div class="progress-bar stripes">
            <span style="width: 0%"></span>
        </div>
    </div>
    <div id="mobile" class="relative" x-show="isMobile || forceHide">
        <div>
            <div id="home">
                <picture>
                    <source media="(max-width: 600px)" sizes="100vw" srcset="img/bg-mobile.png 1x">
                    <source media="(min-width: 601px)" sizes="100vw" srcset="img/bg-ipad.png 1x, img/bg-ipad@2x.png 2x">
                    <img class="img-fluid img-header" src="img/bg-ipad.png" alt="bg signsofthetimes" style="width: 100%;height: auto;">
                </picture>
                <div class="txttop">Be the first to collect one of 5000 P2E NFT’s
                    from Signs of the Times. Created by the award
                    winning animation studio of Animatic Media.
                </div>
                <div class="battle">
                    <a href="">
                        <picture>
                            <source media="(max-width: 600px)" sizes="100vw" srcset="img/btn-protest.png 1x">
                            <source media="(min-width: 601px)" sizes="100vw" srcset="img/btn-protest-ipad.png 1x, img/btn-protest-ipad.png 2x">
                            <img class="img-fluid img-header" src="img/btn-protest-ipad.png" alt="protest" style="width: 100%;height: auto;">
                        </picture>
                    </a>
                    <a href="">
                        <picture>
                            <source media="(max-width: 600px)" sizes="100vw" srcset="img/btn-battle.png 1x">
                            <source media="(min-width: 601px)" sizes="100vw" srcset="img/btn-battle-ipad.png 1x, img/btn-battle-ipad.png 2x">
                            <img class="img-fluid img-header" src="img/btn-battle-ipad.png" alt="battle" style="width: 100%;height: auto;">
                        </picture>
                    </a>
                    <a href="">
                        <picture>
                            <source media="(max-width: 600px)" sizes="100vw" srcset="img/btn-earn.png 1x">
                            <source media="(min-width: 601px)" sizes="100vw" srcset="img/btn-earn-ipad.png 1x, img/btn-earn-ipad.png 2x">
                            <img class="img-fluid img-header" src="img/btn-earn-ipad.png" alt="earn" style="width: 100%;height: auto;">
                        </picture>
                    </a>
                </div>
                <a href="#frmSignup" class="btn" id="signup" rel="modal:open">Sign-up today</a>
                <!-- <img class="" src="img/Red-Camo-Guy-Idle-Cheer.gif" alt="" style="width: 100%;height: auto;position:absolute;top:0;">  -->
            </div>
            <div class="footer absolute text-center text-white left-0 right-0 bottom-[20px] text-[11px] montserrat">SIGNS OF THE TIMES&trade; is a Animatic Media Production<br>Made in Pompano Beach Florida</div>

            <div id="frmSignup" class="modal !absolute top-1/2 left-1/2 -mt-[230px] -ml-[220px]">
                <div class="join">Join the whitelist</div>
                <div>
                    <input type="text" id="name" placeholder="First name">
                    <input type="text" id="email" placeholder="Email address">
                    <span id="error" class="text-white text-[12px]"></span>
                    <button type="submit" class="btn" id="submit">Submit</button>
                </div>
                <div class="txt">* Your email will not be used for any solicitation of any kind.</div>
            </div>
            <div id="success" class="modal !absolute top-1/2 left-1/2 -mt-[230px] -ml-[220px]">
                <div class="join">Success</div>
                <div class="txt">* Your email will not be used for any solicitation of any kind.</div>
            </div>
            <div id="video" class="modal !w-full !max-w-full !p-0 -ml-[40px]">
                <div class="vimeo-full-width pb-[56.25%] px-0 pt-0 relative">
                    <iframe class="absolute top-0 left-0 w-full h-full" src="https://player.vimeo.com/video/699978598" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>

    <script src="/extras/src/settings.js" charset="utf-8"></script>

    <script src="/extras/main.js" charset="utf-8"></script>
    <script type="text/javascript">
        (function() {
            // open web debugger console
            if (typeof VConsole !== 'undefined') {
                window.vConsole = new VConsole();
            }

            var debug = window._CCSettings.debug;
            var splash = document.getElementById('splash');
            splash.style.display = 'block';

            function loadScript(moduleName, cb) {
                function scriptLoaded() {
                    document.body.removeChild(domScript);
                    domScript.removeEventListener('load', scriptLoaded, false);
                    cb && cb();
                };
                var domScript = document.createElement('script');
                domScript.async = true;
                domScript.src = moduleName;
                domScript.addEventListener('load', scriptLoaded, false);
                document.body.appendChild(domScript);
            }

            loadScript(debug ? '/extras/cocos2d-js.js' : '/extras/cocos2d-js-min.js', function() {
                if (CC_PHYSICS_BUILTIN || CC_PHYSICS_CANNON) {
                    loadScript(debug ? '/extras/physics.js' : '/extras/physics-min.js', window.boot);
                } else {
                    window.boot();
                }
            });

        })();

    </script>
    <script type="text/javascript">
        window.captureEmail = function(email, name) {
            axios.post('/api/mails', {
                email
                , name
            }).then(response => {
                console.log(response.data);
            });
        }

        $(document).ready(function() {
            $("#submit").click(function() {
                var testEmail = /^[A-Z0-9._%+-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i;

                var name = $("#name").val();
                var email = $("#email").val();

                if (name.trim() == "") {
                    $("#error").text("Please enter name.");
                    return;
                }

                if (!testEmail.test(email)) {
                    $("#error").text("Invalid email.");
                    return;
                }

                axios.post('/api/mails', {
                    email
                    , name
                }).then(response => {
                    $("#email").val("");
                    $("#name").val("");

                    $("#frmSignup").modal('hide');
                    $("#success").modal('show');
                });
            });
        });

        $(".battle a").click(function() {
            $("#video").modal('show');
            return false;
        });

    </script>
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/index2.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  <title>Cocos Creator | client</title>

  <!--http://www.html5rocks.com/en/mobile/mobifying/-->
  <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1, minimum-scale=1,maximum-scale=1"/>

  <!--https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="format-detection" content="telephone=no">

  <!-- force webkit on 360 -->
  <meta name="renderer" content="webkit"/>
  <meta name="force-rendering" content="webkit"/>
  <!-- force edge on IE -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta name="msapplication-tap-highlight" content="no">

  <!-- force full screen on some browser -->
  <meta name="full-screen" content="yes"/>
  <meta name="x5-fullscreen" content="true"/>
  <meta name="360-fullscreen" content="true"/>
  
  <!-- force screen orientation on some browser -->
  <meta name="screen-orientation" content=""/>
  <meta name="x5-orientation" content="">

  <!--fix fireball/issues/3568 -->
  <!--<meta name="browsermode" content="application">-->
  <meta name="x5-page-mode" content="app">

  <!--<link rel="apple-touch-icon" href=".png" />-->
  <!--<link rel="apple-touch-icon-precomposed" href=".png" />-->

  <link rel="stylesheet" type="text/css" href="/extras/style-mobile.css"/>
  <link rel="icon" href="favicon.ico"/>
</head>
<body>
  <canvas id="GameCanvas" oncontextmenu="event.preventDefault()" tabindex="0"></canvas>
  <div id="splash">
    <div class="progress-bar stripes">
      <span style="width: 0%"></span>
    </div>
  </div>

<script src="/extras/src/settings.js" charset="utf-8"></script>

<script src="/extras/main.js" charset="utf-8"></script>

<script type="text/javascript">
(function () {
    // open web debugger console
    if (typeof VConsole !== 'undefined') {
        window.vConsole = new VConsole();
    }

    var debug = window._CCSettings.debug;
    var splash = document.getElementById('splash');
    splash.style.display = 'block';

    function loadScript (moduleName, cb) {
      function scriptLoaded () {
          document.body.removeChild(domScript);
          domScript.removeEventListener('load', scriptLoaded, false);
          cb && cb();
      };
      var domScript = document.createElement('script');
      domScript.async = true;
      domScript.src = moduleName;
      domScript.addEventListener('load', scriptLoaded, false);
      document.body.appendChild(domScript);
    }

    loadScript(debug ? '/extras/cocos2d-js.js' : '/extras/cocos2d-js-min.js', function () {
      if (CC_PHYSICS_BUILTIN || CC_PHYSICS_CANNON) {
        loadScript(debug ? '/extras/physics.js' : '/extras/physics-min.js', window.boot);
      }
      else {
        window.boot();
      }
    });
})();
</script>
</body>
</html>

resources/views/layout/canvas-menu.blade.php
<div class="absolute w-full bg-white">
test
</div>

resources/views/layout/logo.blade.php
<div id="header-menu" class="absolute w-full bg-transparent z-10">
    <div class="menu max-w-full mx-auto pl-0 sm-max:pl-4 px-4 -mt-[75px]">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <a href="/" class="flex items-center py-4 px-2">
                    <img src="/img/logo.png" alt="Logo" class="logo lg-max:w-[55%] lg-max:m-0 bg-transparent mr-2">
                </a> <!-- Primary Navbar items -->
            </div>
        </div>
    </div>
    <!-- mobile menu -->

</div>

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>A NFT Play-to-earn-game</title>
    <link rel="stylesheet" href="/css/app.css" />
    @yield('header_includes')
    @livewireStyles
</head>
<body class="antialiased bg-black dark:bg-black">
    @includeWhen(!empty($header) && $header === 'logo', 'layout.logo')
    @includeUnless(!empty($header), 'layout.menu')
    @yield('content')
    @livewireScripts
    @yield('footer_includes')
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>
<body class="font-sans antialiased">
    <div class="min-h-screen bg-black">
        @include('layout.logo')

        @include('layouts.navigation')

        <!-- Page Heading -->
        <header class="bg-black shadow hidden">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                {{ $header }}
            </div>
        </header>

        <!-- Page Content -->
        <main>
            {{ $slot }}
        </main>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>
<body class="bg-black dark:bg-black">
    @include('layout.logo')
    <div class="font-sans text-gray-900 antialiased">
        {{ $slot }}
    </div>
</body>
</html>